openapi: "3.0.3"
info:
  title: Felhőkarcolók API
  version: 1.0.0
  description: API a felhőkarcolók kezeléséhez

servers:
  - url: http://backend.vm1.test
    description: VM1 backend
  - url: http://backend.vm2.test
    description: VM2 backend
  - url: http://backend.vm3.test
    description: VM3 backend
  - url: http://backend.vm4.test
    description: VM4 backend
  - url: http://backend.vm5.test
    description: VM5 backend

paths:
  /skyscrapers:
    get:
      summary: Felhőkarcolók listázása
      operationId: getSkyscrapers
      tags:
        - Skyscrapers
      responses:
        '200':
          description: Sikeres lekérdezés
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Skyscraper'
              examples:
                example-1:
                  value:
                    data:
                      - id: 1
                        name: Chrysler Building
                        city:
                          id: 1
                          country_code: US
                          name: New York City
                          skyscrapers:
                            - id: 1
                              name: Chrysler Building
                              height: 318.9
                              stories: 77
                              finished: 1930
                            - id: 2
                              name: Empire State Building
                              height: 381
                              stories: 102
                              finished: 1931
                        height: 318.9
                        stories: 77
                        finished: 1930
                      - id: 2
                        name: Empire State Building
                        city:
                          id: 1
                          country_code: US
                          name: New York City
                          skyscrapers:
                            - id: 1
                              name: Chrysler Building
                              height: 318.9
                              stories: 77
                              finished: 1930
                            - id: 2
                              name: Empire State Building
                              height: 381
                              stories: 102
                              finished: 1931
                        height: 381
                        stories: 102
                        finished: 1931
    post:
      summary: Új felhőkarcoló létrehozása
      operationId: createSkyscraper
      tags:
        - Skyscrapers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SkyscraperInput'
            examples:
              example-1:
                value:
                  name: MOL torony
                  city_id: 37
                  height: 140
                  stories: 25
                  finished: 2000
      responses:
        '201':
          description: Felhőkarcoló létrehozva
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Skyscraper'
              examples:
                example-1:
                  value:
                    data:
                      id: 101
                      name: MOL torony
                      city:
                        id: 37
                        country_code: HU
                        name: Budapest
                        skyscrapers:
                          - id: 101
                            name: MOL torony
                            height: 140
                            stories: 25
                            finished: 2000
                      height: 140
                      stories: 25
                      finished: 2000
  /skyscrapers/{skyscraper}:
    get:
      summary: Felhőkarcoló lekérdezése azonosító alapján
      operationId: getSkyscraperById
      tags:
        - Skyscrapers
      parameters:
        - name: skyscraper
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Sikeres lekérdezés
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Skyscraper'
              examples:
                example-1:
                  value:
                    data:
                      id: 1
                      name: Chrysler Building
                      city:
                        id: 1
                        country_code: US
                        name: New York City
                        skyscrapers:
                          - id: 1
                            name: Chrysler Building
                            height: 318.9
                            stories: 77
                            finished: 1930
                          - id: 2
                            name: Empire State Building
                            height: 381
                            stories: 102
                            finished: 1931
                      height: 318.9
                      stories: 77
                      finished: 1930
    put:
      summary: Felhőkarcoló frissítése
      operationId: updateSkyscraper
      tags:
        - Skyscrapers
      parameters:
        - name: skyscraper
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SkyscraperInput'
            examples:
              example-1:
                value:
                  name: MOL campus
                  city_id: 37
                  height: 143
                  stories: 28
                  finished: 2022
      responses:
        '200':
          description: Felhőkarcoló frissítve
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Skyscraper'
              examples:
                example-1:
                  value:
                    data:
                      id: 101
                      name: MOL campus
                      city:
                        id: 37
                        country_code: HU
                        name: Budapest
                        skyscrapers:
                          - id: 101
                            name: MOL campus
                            height: 143
                            stories: 28
                            finished: 2022
                      height: 143
                      stories: 28
                      finished: 2022
    delete:
      summary: Felhőkarcoló törlése
      operationId: deleteSkyscraper
      tags:
        - Skyscrapers
      parameters:
        - name: skyscraper
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Felhőkarcoló törölve
  /cities:
    get:
      summary: Városok listázása
      operationId: getCities
      tags:
        - Cities
      responses:
        '200':
          description: Sikeres lekérdezés
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/City'
              examples:
                example-1:
                  value:
                    data:
                      - id: 1
                        country_code: US
                        name: New York City
                        skyscrapers:
                          - id: 1
                            name: Chrysler Building
                            height: 318.9
                            stories: 77
                            finished: 1930
                          - id: 2
                            name: Empire State Building
                            height: 381
                            stories: 102
                            finished: 1931
                      - id: 2
                        country_code: HU
                        name: Budapest
                        skyscrapers:
                          - id: 101
                            name: MOL torony
                            height: 140
                            stories: 25
                            finished: 2000
    post:
      summary: Új város létrehozása
      operationId: createCity
      tags:
        - Cities
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CityInput'
            examples:
              example-1:
                value:
                  country_code: HU
                  name: Budapest
      responses:
        '201':
          description: Város létrehozva
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/City'
              examples:
                example-1:
                  value:
                    data:
                      id: 2
                      country_code: HU
                      name: Budapest
                      skyscrapers:
                        - id: 101
                          name: MOL torony
                          height: 140
                          stories: 25
                          finished: 2000
  /cities/{city}:
    get:
      summary: Város lekérdezése azonosító alapján
      operationId: getCityById
      tags:
        - Cities
      parameters:
        - name: city
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Sikeres lekérdezés
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/City'
              examples:
                example-1:
                  value:
                    data:
                      id: 1
                      country_code: US
                      name: New York City
                      skyscrapers:
                        - id: 1
                          name: Chrysler Building
                          height: 318.9
                          stories: 77
                          finished: 1930
                        - id: 2
                          name: Empire State Building
                          height: 381
                          stories: 102
                          finished: 1931
  
    put:
      summary: Város frissítése
      operationId: updateCity
      tags:
        - Cities
      parameters:
        - name: city
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CityInput'
            examples:
              example-1:
                value:
                  country_code: HU
                  name: Budapest
      responses:
        '200':
          description: Város frissítve
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/City'
              examples:
                example-1:
                  value:
                    data:
                      id: 2
                      country_code: HU
                      name: Budapest
                      skyscrapers:
                        - id: 101
                          name: MOL torony
                          height: 140
                          stories: 25
                          finished: 2000
    delete:
      summary: Város törlése
      operationId: deleteCity
      tags:
        - Cities
      parameters:
        - name: city
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Város törölve
components:
  schemas:
    Skyscraper:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        city:
          $ref: '#/components/schemas/City'
        height:
          type: number
        stories:
          type: integer
        finished:
          type: integer
    SkyscraperInput:
      type: object
      properties:
        name:
          type: string
        city_id:
          type: integer
        height:
          type: number
        stories:
          type: integer
        finished:
          type: integer
    City:
      type: object
      properties:
        id:
          type: integer
        country_code:
          type: string
        name:
          type: string
        skyscrapers:
          type: array
          items:
            $ref: '#/components/schemas/Skyscraper'
    CityInput:
      type: object
      properties:
        country_code:
          type: string
        name:
          type: string